### ISSUE TITLE
Bug when login with github

### ISSUE THREAD

**Issue by DaddyAdri** [gitdoapp/Feedback#1]
When log in, the app asks me for de autentification from github, ask me about permissions from github, but returns to the log in screenshot automatically after giving my permission. Fix it :santa:

**Comment by isaacroldan** [comment]
This is both a feature and a bug :trollface: 
It goes back to the login screen, but in background is loading your repos and stuff, it should (eventually) push to the next view after a few seconds.

The login and getting started screens are not done done yet :D

Thanks @DaddyAdri

**Comment by pepibumur** [comment]
Fixed @DaddyAdri
