### ISSUE TITLE
login error authenticating first time

### ISSUE THREAD

**Issue by zanona** [gitdoapp/Feedback#13]
http://cl.ly/fI67

**Comment by VicenteBorrell** [comment]
Sorry @zanona. Maybe the two-factor authentication isn't working. We'll fix it and notify you ASAP. Thanks a lot for the feedback!

**Comment by pepibumur** [comment]
Hi @zanona , should be fixed now, can you try again? :), thanks for reporting!

**Comment by zanona** [comment]
its works nicely now. thanks guys
