### ISSUE TITLE
TestFlight feedback is not working

### ISSUE THREAD

**Issue by isaacroldan** [gitdoapp/feedback#20]
## Bug

Seems like support@gitdo.io (the email setted to receive feedback via TestFlight) does not exists.

#### Other comments

**Comment by pepibumur** [comment]
Fixed @isaacroldan https://github.com/gitdoapp/gitdoapp/commit/5afd07a7c47ecedcb9917d92ad008bcfb17230c9

**Comment by pepibumur** [comment]
The Testflight email is pointing to `help@gitdo.io`
