### ISSUE TITLE
Order of the organizations when adding a repository

### ISSUE THREAD

**Issue by poolqf** [gitdoapp/feedback#3]
The order of the organizations when adding a new repository is totally random :trollface: 

My suggestion would be:
- user
- other organizations ordered A-Z

**Comment by pepibumur** [comment]
great!, good idea @poolqf :stuck_out_tongue:

**Comment by VicenteBorrell** [comment]
Thanks @poolqf !

**Comment by VicenteBorrell** [comment]
Fixed? @pepibumur

**Comment by pepibumur** [comment]
@poolqf which order would you suggest?

**Comment by pepibumur** [comment]
Ohps sorry I didn't see the order
