### ISSUE TITLE
Can't see my repos

### ISSUE THREAD

**Issue by nandodelauni** [gitdoapp/Feedback#4]
I can't select any repo to add it into Repositories' tab because I don't see any.

<img src="https://cloud.githubusercontent.com/assets/1938501/10922317/bae87d50-827a-11e5-9d3b-7e50a5278295.png" width=300 /img>

App version - 0.1.2 (31)

**Comment by pepibumur** [comment]
@nandodelauni if you close/reopen the app still happening?

**Comment by nandodelauni** [comment]
yep

**Comment by pepibumur** [comment]
Logging out & in?

**Comment by nandodelauni** [comment]
nope

**Comment by isaacroldan** [comment]
do you have any repo? :trollface:

**Comment by nandodelauni** [comment]
public and private motherflecker! 😁

**Comment by pepibumur** [comment]
Are you banned @nandodelauni ? :trollface:

**Comment by nandodelauni** [comment]
curious, i've received a push notification for a new issue opened in one of my repos. I guess that the repo was selected in one of the older version. I've deleted the app and re-installed and and one repo shows up and all the repos are shown if tap the + button.

Maybe this is an incosistency betwen database schemas? Feel free to close it.

**Comment by isaacroldan** [comment]
Probably, did you uninstall the previous version before installing the last beta? A lot changed

**Comment by pepibumur** [comment]
hahahah I was going to ask the same @isaacroldan

**Comment by nandodelauni** [comment]
no, the release notes didn't say anything about that or at least I didn't notice 😈

**Comment by pepibumur** [comment]
:trollface: that's right ~> Migration support soon.

**Comment by nandodelauni** [comment]
fair enough!

**Comment by VicenteBorrell** [comment]
Thanks anyway @nandodelauni ! Give us more feedback!
