### ISSUE TITLE
Is commenting on individual issues supported?

### ISSUE THREAD

**Issue by jjmata** [gitdoapp/Feedback#9]
Kind of a bit let down if it isn't ... :cry:

**Comment by isaacroldan** [comment]
Yes, it is, but right now, opening an issue from the kanban is broken. This sunday we will send a new version with that fixed. You will be able to see the full detail of an Issue, all the comments and write new comments :)

**Comment by jjmata** [comment]
What a difference!  The app seemed quite broken without that ...
